ALTER TABLE deals ADD COLUMN IF NOT EXISTS commission_rate NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS commission_amount NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS buyer_agent TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS listing_agent TEXT;
